language: go
go:
  - 1.9.2
before_script:
  - go vet ./...
notifications:
  email: false
  slack:
    rooms:
      - freecloudio:toiPOnFnf5xCG8larulu8XPb#server
    on_success: change
    on_failure: always