dist: xenial
language: go
git:
  depth: false
services:
  - neo4j
addons:
  sonarcloud:
    organization: "freecloudio"
    token:
      secure: "N0e4mzUJncFnm+i9LZ2dKxNRID7/itLbAA6QxkkijnfkElq2lMj9q6gJqBRueb449Z1xVV61hR6IGVnmo0DEiDSVTYEzuKr9JCIVfSn/qcgZcJsAfejiMTxH7B84JIIxxXwCfTj/gO41dMdm6fk32LY3SQe88NAlW7lOFSX/cISxJilJbbS2kBhcRectSXjBlsQ3KZmlY2W6AkRA1AqSbE9ogNmSdIxWf9R14qSO1RMXpixKu4FrrTc6J4NHxzdGvkSas+KVVLqGvvF8T24CmEu5YJvDpzO51328gRVzxtWgBx45285E6PNHW9tZqsVTGfx6BXPpxSkIayfonrfFIbizrVEJ4z76lRq0H6loYj12FQH3+PZfln7/DWZYK2VV1GQ2s0C8byJlFHZPqkWZUAyjMIK6n3nxP/GirFMdoh67jBoqPqsg0FpfdV80IndM/qbwzl5ZJ7jk2hwTTWS8ZlzjDIMe+YTmaHUOAAysw/AIPXVx7Mi4E2nOURpjkV9Pjnl877AX5BL+TQz527ev6vsoZDKGgLpyKg/zZ85ooMkqdZ0TSw2W4H+ZtBRyN2IVgRJ35t+ah15c+c0v5sOP196AD98iY5mWE2Ul6bvEKrTRfohG7bGAZMc3hU6oeYSDUdv1wx8UH8EwZ+GGg3l0vVH8lnGbQqoKBTBfp+WR1sM=" 
go:
  - "1.x"
  - "1.10.x"
  - "1.10"
before_script:
  - git fetch origin master:refs/remotes/origin/master
  - sudo apt-get install -y libssl1.0.0
  - wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.0/seabolt-1.7.0-Linux-Ubuntu-Xenial.deb
  - sudo dpkg -i seabolt-1.7.0-Linux-Ubuntu-Xenial.deb
script:
  - go vet ./... 2> vet_report.out
  - go build ./cmd/freecloud-server
#  - go test -coverprofile=test_coverage.out -json -race ./... > test_report.json
#  - sonar-scanner
notifications:
  email: false
  slack:
    rooms:
      secure: Vec6ZLGUQou4kiFu7aPrJ3ZHPOHOrg8odM6qoBcpizKJG21wOazoTtZL1CcQ/aMemZplVZqw9fGbfZDMt80EkhfB7ES7B9MTdzwijzkdd16xr5AnsGkuFnAZHIs4JIbxMoJnse6gdYvyq58hif3RsDqFjLUfQvA7ASRO0/MCdwv15uHPCJCbV43G/5Is3Mq3A0sWpl5dsiony82CBDwE/S328U8W7CIZt/eOjV/CEY8NDAodtBZeIKz8NbkFOnqwz8tn3isXZtjXnIpLspI7gO3V5TvGzPRp/XMwWXWC6t2DY6G5V0230uza8+VIagle5e8CGv/825mQf50/yM64rFYFg22gl+uTlQd+Yw0nQA+3wjRzAd6ZrOyUWMonwmd/ClQjMUxq4AnzGhTE6brIvID1KEAJ+EUHPryVmmXlT8wJsaWw/kPRkNy6+nStCJbhS2ScsG4ljA2/qH+sW/A14Ukhu2MkLopgaFvzxFN7XX0e7K5vdJ+sBBfw4o2knFS+BddsarRoRgM6ZSi35nebYBRIPk1RNhFFeuTlpmZtVXCJM4NJgM0pHShy1LkO5zMVV33OKGz6oTJkPzc0QgWuMkBPARuGVVFBQ90QuxCH2mSagANsW3aHvFaTRiJpRycuBsAc0w7e7YdHCUJEQBzs6uPY5WEJNRjnj5XSPjo2GVY=
    on_success: change
    on_failure: always