language: go
go:
- "1.x"
- "1.10.x"
- "1.10"
before_script:
- go vet ./...
script: go test -race -v ./...
notifications:
  email: false
  slack:
    rooms:
      secure: Vec6ZLGUQou4kiFu7aPrJ3ZHPOHOrg8odM6qoBcpizKJG21wOazoTtZL1CcQ/aMemZplVZqw9fGbfZDMt80EkhfB7ES7B9MTdzwijzkdd16xr5AnsGkuFnAZHIs4JIbxMoJnse6gdYvyq58hif3RsDqFjLUfQvA7ASRO0/MCdwv15uHPCJCbV43G/5Is3Mq3A0sWpl5dsiony82CBDwE/S328U8W7CIZt/eOjV/CEY8NDAodtBZeIKz8NbkFOnqwz8tn3isXZtjXnIpLspI7gO3V5TvGzPRp/XMwWXWC6t2DY6G5V0230uza8+VIagle5e8CGv/825mQf50/yM64rFYFg22gl+uTlQd+Yw0nQA+3wjRzAd6ZrOyUWMonwmd/ClQjMUxq4AnzGhTE6brIvID1KEAJ+EUHPryVmmXlT8wJsaWw/kPRkNy6+nStCJbhS2ScsG4ljA2/qH+sW/A14Ukhu2MkLopgaFvzxFN7XX0e7K5vdJ+sBBfw4o2knFS+BddsarRoRgM6ZSi35nebYBRIPk1RNhFFeuTlpmZtVXCJM4NJgM0pHShy1LkO5zMVV33OKGz6oTJkPzc0QgWuMkBPARuGVVFBQ90QuxCH2mSagANsW3aHvFaTRiJpRycuBsAc0w7e7YdHCUJEQBzs6uPY5WEJNRjnj5XSPjo2GVY=
    on_success: change
    on_failure: always