language: go
go:
  - 1.9.2
before_script:
  - go vet ./...
notifications:
  email: false
  slack:
    secure: L8HUOX/qgf6z+WKQgfViWIYjP7Hx4C9z1mePoH3251D/JPzZQ1NsH0qXp3VwCvOei3C8XiETdl51AMOAh4J6xbPVv5ppF6Crs45K9M5e8+S20HhjCJsQv70MWI2a3CYDNTWo1J5hxyYmMXDQTsLVrbW6ncw5eW13fySN6zQcq4mRfB7xj6GpoB6mNHTMJEZB/UnlNy9GDRj9DWU8xUJLmED/DzDekqOQ4YT82fadbD9CLPsDlmkXCWsyDn9GDDg97g2HMxExFjkxSrXZsnn3JJhuSYYXZ4YoqGsple7faMzC4D64f4WZKhWmPkplStDmNXcXpn6FmnhrxVQbEILkm4qsBG3g+7HW9X9TfYJz4rgXIBTVlIJSIuKamV4Tq1dt5zlsm4raeBKL1MJbgce0BOZmnBmvu02Wo8VnFOKzJ5HA3P3fbo8E6vk9ncxv68K88Buu/j3+wsA0w5oFpp5SxNh2syRPjI1/yqVuRhKnNZ/4mWpXKAykMvArz58diVDdAVFylXHVsRD8QchEzHHyjZIekBfs5D/WCp13h5iYWhhuy0Z7q/uXwTc50aH4lkngfQ2/af26qNbNe9J8KlrAZaOsivJkp7dGOaKZZbBvkkkwDlcgw7LE05cnPWcceStN82zhLYaud8+2/XXWJCtbDXXpEYwsZyd4yLnCb0borBw=
    on_success: change
    on_failure: always