// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi freecloud API
This is the API for the freecloud server.


    Schemes:
      http
      https
    Host: freecloud.glidingthrough.space
    BasePath: /api/v1
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/gzip
    - application/json

swagger:meta
*/
package restapi
