// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/freecloud/models"
)

// DeleteCurrentUserOKCode is the HTTP code returned for type DeleteCurrentUserOK
const DeleteCurrentUserOKCode int = 200

/*DeleteCurrentUserOK Success

swagger:response deleteCurrentUserOK
*/
type DeleteCurrentUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewDeleteCurrentUserOK creates DeleteCurrentUserOK with default headers values
func NewDeleteCurrentUserOK() *DeleteCurrentUserOK {

	return &DeleteCurrentUserOK{}
}

// WithPayload adds the payload to the delete current user o k response
func (o *DeleteCurrentUserOK) WithPayload(payload *models.User) *DeleteCurrentUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete current user o k response
func (o *DeleteCurrentUserOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCurrentUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteCurrentUserDefault Unexpected error

swagger:response deleteCurrentUserDefault
*/
type DeleteCurrentUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteCurrentUserDefault creates DeleteCurrentUserDefault with default headers values
func NewDeleteCurrentUserDefault(code int) *DeleteCurrentUserDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteCurrentUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete current user default response
func (o *DeleteCurrentUserDefault) WithStatusCode(code int) *DeleteCurrentUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete current user default response
func (o *DeleteCurrentUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete current user default response
func (o *DeleteCurrentUserDefault) WithPayload(payload *models.Error) *DeleteCurrentUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete current user default response
func (o *DeleteCurrentUserDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCurrentUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
