// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/freecloudio/server/models"
)

// DeleteUserByUsernameHandlerFunc turns a function with the right signature into a delete user by username handler
type DeleteUserByUsernameHandlerFunc func(DeleteUserByUsernameParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserByUsernameHandlerFunc) Handle(params DeleteUserByUsernameParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteUserByUsernameHandler interface for that can handle valid delete user by username params
type DeleteUserByUsernameHandler interface {
	Handle(DeleteUserByUsernameParams, *models.Principal) middleware.Responder
}

// NewDeleteUserByUsername creates a new http.Handler for the delete user by username operation
func NewDeleteUserByUsername(ctx *middleware.Context, handler DeleteUserByUsernameHandler) *DeleteUserByUsername {
	return &DeleteUserByUsername{Context: ctx, Handler: handler}
}

/*DeleteUserByUsername swagger:route DELETE /user/{username} user deleteUserByUsername

Delete user by username

*/
type DeleteUserByUsername struct {
	Context *middleware.Context
	Handler DeleteUserByUsernameHandler
}

func (o *DeleteUserByUsername) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteUserByUsernameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
