// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/server/models"
)

// DeleteUserByUsernameOKCode is the HTTP code returned for type DeleteUserByUsernameOK
const DeleteUserByUsernameOKCode int = 200

/*DeleteUserByUsernameOK Success

swagger:response deleteUserByUsernameOK
*/
type DeleteUserByUsernameOK struct {
}

// NewDeleteUserByUsernameOK creates DeleteUserByUsernameOK with default headers values
func NewDeleteUserByUsernameOK() *DeleteUserByUsernameOK {

	return &DeleteUserByUsernameOK{}
}

// WriteResponse to the client
func (o *DeleteUserByUsernameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*DeleteUserByUsernameDefault Unexpected error

swagger:response deleteUserByUsernameDefault
*/
type DeleteUserByUsernameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserByUsernameDefault creates DeleteUserByUsernameDefault with default headers values
func NewDeleteUserByUsernameDefault(code int) *DeleteUserByUsernameDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserByUsernameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user by username default response
func (o *DeleteUserByUsernameDefault) WithStatusCode(code int) *DeleteUserByUsernameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user by username default response
func (o *DeleteUserByUsernameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user by username default response
func (o *DeleteUserByUsernameDefault) WithPayload(payload *models.Error) *DeleteUserByUsernameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user by username default response
func (o *DeleteUserByUsernameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserByUsernameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
