// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/server/models"
)

// DeleteUserByIDOKCode is the HTTP code returned for type DeleteUserByIDOK
const DeleteUserByIDOKCode int = 200

/*DeleteUserByIDOK Success

swagger:response deleteUserByIdOK
*/
type DeleteUserByIDOK struct {
}

// NewDeleteUserByIDOK creates DeleteUserByIDOK with default headers values
func NewDeleteUserByIDOK() *DeleteUserByIDOK {

	return &DeleteUserByIDOK{}
}

// WriteResponse to the client
func (o *DeleteUserByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*DeleteUserByIDDefault Unexpected error

swagger:response deleteUserByIdDefault
*/
type DeleteUserByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserByIDDefault creates DeleteUserByIDDefault with default headers values
func NewDeleteUserByIDDefault(code int) *DeleteUserByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user by ID default response
func (o *DeleteUserByIDDefault) WithStatusCode(code int) *DeleteUserByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user by ID default response
func (o *DeleteUserByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user by ID default response
func (o *DeleteUserByIDDefault) WithPayload(payload *models.Error) *DeleteUserByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user by ID default response
func (o *DeleteUserByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
