// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/freecloudio/server/models"
)

// GetUserByUsernameHandlerFunc turns a function with the right signature into a get user by username handler
type GetUserByUsernameHandlerFunc func(GetUserByUsernameParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserByUsernameHandlerFunc) Handle(params GetUserByUsernameParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetUserByUsernameHandler interface for that can handle valid get user by username params
type GetUserByUsernameHandler interface {
	Handle(GetUserByUsernameParams, *models.Principal) middleware.Responder
}

// NewGetUserByUsername creates a new http.Handler for the get user by username operation
func NewGetUserByUsername(ctx *middleware.Context, handler GetUserByUsernameHandler) *GetUserByUsername {
	return &GetUserByUsername{Context: ctx, Handler: handler}
}

/*GetUserByUsername swagger:route GET /user/{username} user getUserByUsername

Get specific user by username

*/
type GetUserByUsername struct {
	Context *middleware.Context
	Handler GetUserByUsernameHandler
}

func (o *GetUserByUsername) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserByUsernameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
