// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/server/models"
)

// UpdateUserByUsernameOKCode is the HTTP code returned for type UpdateUserByUsernameOK
const UpdateUserByUsernameOKCode int = 200

/*UpdateUserByUsernameOK Success

swagger:response updateUserByUsernameOK
*/
type UpdateUserByUsernameOK struct {
}

// NewUpdateUserByUsernameOK creates UpdateUserByUsernameOK with default headers values
func NewUpdateUserByUsernameOK() *UpdateUserByUsernameOK {

	return &UpdateUserByUsernameOK{}
}

// WriteResponse to the client
func (o *UpdateUserByUsernameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*UpdateUserByUsernameDefault Unexpected error

swagger:response updateUserByUsernameDefault
*/
type UpdateUserByUsernameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserByUsernameDefault creates UpdateUserByUsernameDefault with default headers values
func NewUpdateUserByUsernameDefault(code int) *UpdateUserByUsernameDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateUserByUsernameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update user by username default response
func (o *UpdateUserByUsernameDefault) WithStatusCode(code int) *UpdateUserByUsernameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update user by username default response
func (o *UpdateUserByUsernameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update user by username default response
func (o *UpdateUserByUsernameDefault) WithPayload(payload *models.Error) *UpdateUserByUsernameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user by username default response
func (o *UpdateUserByUsernameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserByUsernameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
