// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/freecloud/models"
)

// CreateFileOKCode is the HTTP code returned for type CreateFileOK
const CreateFileOKCode int = 200

/*CreateFileOK Success

swagger:response createFileOK
*/
type CreateFileOK struct {
}

// NewCreateFileOK creates CreateFileOK with default headers values
func NewCreateFileOK() *CreateFileOK {

	return &CreateFileOK{}
}

// WriteResponse to the client
func (o *CreateFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*CreateFileDefault Unexpected error

swagger:response createFileDefault
*/
type CreateFileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateFileDefault creates CreateFileDefault with default headers values
func NewCreateFileDefault(code int) *CreateFileDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateFileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create file default response
func (o *CreateFileDefault) WithStatusCode(code int) *CreateFileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create file default response
func (o *CreateFileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create file default response
func (o *CreateFileDefault) WithPayload(payload *models.Error) *CreateFileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create file default response
func (o *CreateFileDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateFileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
