// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/freecloudio/freecloud/models"
)

// DeleteFileHandlerFunc turns a function with the right signature into a delete file handler
type DeleteFileHandlerFunc func(DeleteFileParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteFileHandlerFunc) Handle(params DeleteFileParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteFileHandler interface for that can handle valid delete file params
type DeleteFileHandler interface {
	Handle(DeleteFileParams, *models.User) middleware.Responder
}

// NewDeleteFile creates a new http.Handler for the delete file operation
func NewDeleteFile(ctx *middleware.Context, handler DeleteFileHandler) *DeleteFile {
	return &DeleteFile{Context: ctx, Handler: handler}
}

/*DeleteFile swagger:route DELETE /file file deleteFile

Delete file/folder

*/
type DeleteFile struct {
	Context *middleware.Context
	Handler DeleteFileHandler
}

func (o *DeleteFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteFileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
