// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/freecloudio/server/models"
)

// DeleteShareEntryByIDHandlerFunc turns a function with the right signature into a delete share entry by ID handler
type DeleteShareEntryByIDHandlerFunc func(DeleteShareEntryByIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteShareEntryByIDHandlerFunc) Handle(params DeleteShareEntryByIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteShareEntryByIDHandler interface for that can handle valid delete share entry by ID params
type DeleteShareEntryByIDHandler interface {
	Handle(DeleteShareEntryByIDParams, *models.Principal) middleware.Responder
}

// NewDeleteShareEntryByID creates a new http.Handler for the delete share entry by ID operation
func NewDeleteShareEntryByID(ctx *middleware.Context, handler DeleteShareEntryByIDHandler) *DeleteShareEntryByID {
	return &DeleteShareEntryByID{Context: ctx, Handler: handler}
}

/*DeleteShareEntryByID swagger:route DELETE /file/share/{shareID} file deleteShareEntryById

Delete share entry by shareID

*/
type DeleteShareEntryByID struct {
	Context *middleware.Context
	Handler DeleteShareEntryByIDHandler
}

func (o *DeleteShareEntryByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteShareEntryByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
