// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/server/models"
)

// GetShareEntryByIDOKCode is the HTTP code returned for type GetShareEntryByIDOK
const GetShareEntryByIDOKCode int = 200

/*GetShareEntryByIDOK Share entry

swagger:response getShareEntryByIdOK
*/
type GetShareEntryByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ShareEntry `json:"body,omitempty"`
}

// NewGetShareEntryByIDOK creates GetShareEntryByIDOK with default headers values
func NewGetShareEntryByIDOK() *GetShareEntryByIDOK {

	return &GetShareEntryByIDOK{}
}

// WithPayload adds the payload to the get share entry by Id o k response
func (o *GetShareEntryByIDOK) WithPayload(payload *models.ShareEntry) *GetShareEntryByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get share entry by Id o k response
func (o *GetShareEntryByIDOK) SetPayload(payload *models.ShareEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShareEntryByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetShareEntryByIDDefault Unexpected error

swagger:response getShareEntryByIdDefault
*/
type GetShareEntryByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetShareEntryByIDDefault creates GetShareEntryByIDDefault with default headers values
func NewGetShareEntryByIDDefault(code int) *GetShareEntryByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetShareEntryByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get share entry by ID default response
func (o *GetShareEntryByIDDefault) WithStatusCode(code int) *GetShareEntryByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get share entry by ID default response
func (o *GetShareEntryByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get share entry by ID default response
func (o *GetShareEntryByIDDefault) WithPayload(payload *models.Error) *GetShareEntryByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get share entry by ID default response
func (o *GetShareEntryByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShareEntryByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
