// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetShareEntryByIDParams creates a new GetShareEntryByIDParams object
// no default values defined in spec.
func NewGetShareEntryByIDParams() GetShareEntryByIDParams {

	return GetShareEntryByIDParams{}
}

// GetShareEntryByIDParams contains all the bound params for the get share entry by ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters getShareEntryByID
type GetShareEntryByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Requested shareID
	  Required: true
	  Minimum: 1
	  In: path
	*/
	ShareID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetShareEntryByIDParams() beforehand.
func (o *GetShareEntryByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rShareID, rhkShareID, _ := route.Params.GetOK("shareID")
	if err := o.bindShareID(rShareID, rhkShareID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindShareID binds and validates parameter ShareID from path.
func (o *GetShareEntryByIDParams) bindShareID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("shareID", "path", "int64", raw)
	}
	o.ShareID = value

	if err := o.validateShareID(formats); err != nil {
		return err
	}

	return nil
}

// validateShareID carries on validations for parameter ShareID
func (o *GetShareEntryByIDParams) validateShareID(formats strfmt.Registry) error {

	if err := validate.MinimumInt("shareID", "path", int64(o.ShareID), 1, false); err != nil {
		return err
	}

	return nil
}
