// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/freecloud/models"
)

// GetStarredFileInfosOKCode is the HTTP code returned for type GetStarredFileInfosOK
const GetStarredFileInfosOKCode int = 200

/*GetStarredFileInfosOK Starred file infos

swagger:response getStarredFileInfosOK
*/
type GetStarredFileInfosOK struct {

	/*
	  In: Body
	*/
	Payload *models.FileList `json:"body,omitempty"`
}

// NewGetStarredFileInfosOK creates GetStarredFileInfosOK with default headers values
func NewGetStarredFileInfosOK() *GetStarredFileInfosOK {

	return &GetStarredFileInfosOK{}
}

// WithPayload adds the payload to the get starred file infos o k response
func (o *GetStarredFileInfosOK) WithPayload(payload *models.FileList) *GetStarredFileInfosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get starred file infos o k response
func (o *GetStarredFileInfosOK) SetPayload(payload *models.FileList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStarredFileInfosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetStarredFileInfosDefault Unexpected error

swagger:response getStarredFileInfosDefault
*/
type GetStarredFileInfosDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetStarredFileInfosDefault creates GetStarredFileInfosDefault with default headers values
func NewGetStarredFileInfosDefault(code int) *GetStarredFileInfosDefault {
	if code <= 0 {
		code = 500
	}

	return &GetStarredFileInfosDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get starred file infos default response
func (o *GetStarredFileInfosDefault) WithStatusCode(code int) *GetStarredFileInfosDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get starred file infos default response
func (o *GetStarredFileInfosDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get starred file infos default response
func (o *GetStarredFileInfosDefault) WithPayload(payload *models.Error) *GetStarredFileInfosDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get starred file infos default response
func (o *GetStarredFileInfosDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStarredFileInfosDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
