// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/freecloud/models"
)

// GetPathInfoOKCode is the HTTP code returned for type GetPathInfoOK
const GetPathInfoOKCode int = 200

/*GetPathInfoOK Requested pathInfo

swagger:response getPathInfoOK
*/
type GetPathInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.PathInfo `json:"body,omitempty"`
}

// NewGetPathInfoOK creates GetPathInfoOK with default headers values
func NewGetPathInfoOK() *GetPathInfoOK {

	return &GetPathInfoOK{}
}

// WithPayload adds the payload to the get path info o k response
func (o *GetPathInfoOK) WithPayload(payload *models.PathInfo) *GetPathInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get path info o k response
func (o *GetPathInfoOK) SetPayload(payload *models.PathInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPathInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPathInfoDefault Unexpected error

swagger:response getPathInfoDefault
*/
type GetPathInfoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPathInfoDefault creates GetPathInfoDefault with default headers values
func NewGetPathInfoDefault(code int) *GetPathInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPathInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get path info default response
func (o *GetPathInfoDefault) WithStatusCode(code int) *GetPathInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get path info default response
func (o *GetPathInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get path info default response
func (o *GetPathInfoDefault) WithPayload(payload *models.Error) *GetPathInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get path info default response
func (o *GetPathInfoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPathInfoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
