// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/freecloudio/server/models"
)

// GetFileInfoHandlerFunc turns a function with the right signature into a get file info handler
type GetFileInfoHandlerFunc func(GetFileInfoParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFileInfoHandlerFunc) Handle(params GetFileInfoParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFileInfoHandler interface for that can handle valid get file info params
type GetFileInfoHandler interface {
	Handle(GetFileInfoParams, *models.Principal) middleware.Responder
}

// NewGetFileInfo creates a new http.Handler for the get file info operation
func NewGetFileInfo(ctx *middleware.Context, handler GetFileInfoHandler) *GetFileInfo {
	return &GetFileInfo{Context: ctx, Handler: handler}
}

/*GetFileInfo swagger:route GET /file file getFileInfo

Get fileInfo of requested path

*/
type GetFileInfo struct {
	Context *middleware.Context
	Handler GetFileInfoHandler
}

func (o *GetFileInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFileInfoParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
