// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/freecloud/models"
)

// RescanUserByIDOKCode is the HTTP code returned for type RescanUserByIDOK
const RescanUserByIDOKCode int = 200

/*RescanUserByIDOK Success

swagger:response rescanUserByIdOK
*/
type RescanUserByIDOK struct {
}

// NewRescanUserByIDOK creates RescanUserByIDOK with default headers values
func NewRescanUserByIDOK() *RescanUserByIDOK {

	return &RescanUserByIDOK{}
}

// WriteResponse to the client
func (o *RescanUserByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*RescanUserByIDDefault Unexpected error

swagger:response rescanUserByIdDefault
*/
type RescanUserByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRescanUserByIDDefault creates RescanUserByIDDefault with default headers values
func NewRescanUserByIDDefault(code int) *RescanUserByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &RescanUserByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the rescan user by ID default response
func (o *RescanUserByIDDefault) WithStatusCode(code int) *RescanUserByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the rescan user by ID default response
func (o *RescanUserByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the rescan user by ID default response
func (o *RescanUserByIDDefault) WithPayload(payload *models.Error) *RescanUserByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rescan user by ID default response
func (o *RescanUserByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RescanUserByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
