// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/freecloudio/server/models"
)

// ShareFilesHandlerFunc turns a function with the right signature into a share files handler
type ShareFilesHandlerFunc func(ShareFilesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ShareFilesHandlerFunc) Handle(params ShareFilesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ShareFilesHandler interface for that can handle valid share files params
type ShareFilesHandler interface {
	Handle(ShareFilesParams, *models.Principal) middleware.Responder
}

// NewShareFiles creates a new http.Handler for the share files operation
func NewShareFiles(ctx *middleware.Context, handler ShareFilesHandler) *ShareFiles {
	return &ShareFiles{Context: ctx, Handler: handler}
}

/*ShareFiles swagger:route POST /share file shareFiles

Share files/folders

*/
type ShareFiles struct {
	Context *middleware.Context
	Handler ShareFilesHandler
}

func (o *ShareFiles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShareFilesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
