// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/freecloudio/server/models"
)

// ShareFileHandlerFunc turns a function with the right signature into a share file handler
type ShareFileHandlerFunc func(ShareFileParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ShareFileHandlerFunc) Handle(params ShareFileParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ShareFileHandler interface for that can handle valid share file params
type ShareFileHandler interface {
	Handle(ShareFileParams, *models.Principal) middleware.Responder
}

// NewShareFile creates a new http.Handler for the share file operation
func NewShareFile(ctx *middleware.Context, handler ShareFileHandler) *ShareFile {
	return &ShareFile{Context: ctx, Handler: handler}
}

/*ShareFile swagger:route POST /share file shareFile

Share files/folders

*/
type ShareFile struct {
	Context *middleware.Context
	Handler ShareFileHandler
}

func (o *ShareFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShareFileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
