// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/server/models"
)

// StarredFilesOKCode is the HTTP code returned for type StarredFilesOK
const StarredFilesOKCode int = 200

/*StarredFilesOK Starred files

swagger:response starredFilesOK
*/
type StarredFilesOK struct {

	/*
	  In: Body
	*/
	Payload *models.FileList `json:"body,omitempty"`
}

// NewStarredFilesOK creates StarredFilesOK with default headers values
func NewStarredFilesOK() *StarredFilesOK {

	return &StarredFilesOK{}
}

// WithPayload adds the payload to the starred files o k response
func (o *StarredFilesOK) WithPayload(payload *models.FileList) *StarredFilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the starred files o k response
func (o *StarredFilesOK) SetPayload(payload *models.FileList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StarredFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*StarredFilesDefault Unexpected error

swagger:response starredFilesDefault
*/
type StarredFilesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStarredFilesDefault creates StarredFilesDefault with default headers values
func NewStarredFilesDefault(code int) *StarredFilesDefault {
	if code <= 0 {
		code = 500
	}

	return &StarredFilesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the starred files default response
func (o *StarredFilesDefault) WithStatusCode(code int) *StarredFilesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the starred files default response
func (o *StarredFilesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the starred files default response
func (o *StarredFilesDefault) WithPayload(payload *models.Error) *StarredFilesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the starred files default response
func (o *StarredFilesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StarredFilesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
