// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/freecloudio/freecloud/models"
)

// UpdateFileOKCode is the HTTP code returned for type UpdateFileOK
const UpdateFileOKCode int = 200

/*UpdateFileOK Success

swagger:response updateFileOK
*/
type UpdateFileOK struct {
}

// NewUpdateFileOK creates UpdateFileOK with default headers values
func NewUpdateFileOK() *UpdateFileOK {

	return &UpdateFileOK{}
}

// WriteResponse to the client
func (o *UpdateFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*UpdateFileDefault Unexpected error

swagger:response updateFileDefault
*/
type UpdateFileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateFileDefault creates UpdateFileDefault with default headers values
func NewUpdateFileDefault(code int) *UpdateFileDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateFileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update file default response
func (o *UpdateFileDefault) WithStatusCode(code int) *UpdateFileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update file default response
func (o *UpdateFileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update file default response
func (o *UpdateFileDefault) WithPayload(payload *models.Error) *UpdateFileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update file default response
func (o *UpdateFileDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateFileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
