// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	Signup(ctx context.Context, in *User, opts ...grpc.CallOption) (*Authentication, error)
	Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*Authentication, error)
	Logout(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Signup(ctx context.Context, in *User, opts ...grpc.CallOption) (*Authentication, error) {
	out := new(Authentication)
	err := grpc.Invoke(ctx, "/auth.AuthService/Signup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*Authentication, error) {
	out := new(Authentication)
	err := grpc.Invoke(ctx, "/auth.AuthService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/auth.AuthService/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Signup(context.Context, *User) (*Authentication, error)
	Login(context.Context, *User) (*Authentication, error)
	Logout(context.Context, *Authentication) (*EmptyMessage, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Signup(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Authentication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*Authentication))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _AuthService_Signup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_849bdf88094e7ba8) }

var fileDescriptor_auth_849bdf88094e7ba8 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x78, 0xd3, 0x53, 0xf3, 0x52,
	0x8b, 0x12, 0x73, 0x20, 0x82, 0x52, 0x5c, 0xa5, 0xc5, 0xa9, 0x45, 0x10, 0xb6, 0xd1, 0x2a, 0x46,
	0x2e, 0x6e, 0xc7, 0xd2, 0x92, 0x8c, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x7d, 0x2e,
	0xb6, 0xe0, 0xcc, 0xf4, 0xbc, 0xd2, 0x02, 0x21, 0x2e, 0x3d, 0xb0, 0xb2, 0xd0, 0xe2, 0xd4, 0x22,
	0x29, 0x71, 0x3d, 0x98, 0x09, 0x20, 0xb5, 0xa9, 0x79, 0x25, 0x99, 0xc9, 0x89, 0x25, 0x99, 0xf9,
	0x79, 0x4a, 0x0c, 0x42, 0x7a, 0x5c, 0xac, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0xc4, 0xaa, 0xb7, 0xe2,
	0x62, 0xf3, 0xc9, 0x4f, 0xcf, 0x2f, 0x2d, 0x11, 0xc2, 0xa5, 0x48, 0x4a, 0x14, 0x2e, 0xe1, 0x9a,
	0x5b, 0x50, 0x52, 0xe9, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0xaa, 0xc4, 0xe0, 0xc4, 0x11, 0xc5,
	0x96, 0x9b, 0x9f, 0x92, 0x9a, 0x53, 0x9c, 0xc4, 0x06, 0x76, 0xbd, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x31, 0x47, 0x4d, 0x84, 0xec, 0x00, 0x00, 0x00,
}
