// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CreateFileRequest create file request
// swagger:model CreateFileRequest
type CreateFileRequest struct {

	// full path
	FullPath string `json:"fullPath,omitempty"`

	// is dir
	IsDir bool `json:"isDir,omitempty"`
}

// Validate validates this create file request
func (m *CreateFileRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateFileRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateFileRequest) UnmarshalBinary(b []byte) error {
	var res CreateFileRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
