// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SystemStatsResponse struct {
	Meta                 *DefaultResponse `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Stats                *SystemStats     `protobuf:"bytes,2,opt,name=stats" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SystemStatsResponse) Reset()         { *m = SystemStatsResponse{} }
func (m *SystemStatsResponse) String() string { return proto.CompactTextString(m) }
func (*SystemStatsResponse) ProtoMessage()    {}
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_system_1b356edd64c42dec, []int{0}
}
func (m *SystemStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStatsResponse.Unmarshal(m, b)
}
func (m *SystemStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStatsResponse.Marshal(b, m, deterministic)
}
func (dst *SystemStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStatsResponse.Merge(dst, src)
}
func (m *SystemStatsResponse) XXX_Size() int {
	return xxx_messageInfo_SystemStatsResponse.Size(m)
}
func (m *SystemStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStatsResponse proto.InternalMessageInfo

func (m *SystemStatsResponse) GetMeta() *DefaultResponse {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *SystemStatsResponse) GetStats() *SystemStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type SystemStats struct {
	Version              string             `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	AllocMem             uint64             `protobuf:"varint,2,opt,name=allocMem" json:"allocMem,omitempty"`
	TotalAllocMem        uint64             `protobuf:"varint,3,opt,name=totalAllocMem" json:"totalAllocMem,omitempty"`
	SystemMem            uint64             `protobuf:"varint,4,opt,name=systemMem" json:"systemMem,omitempty"`
	NumGC                uint32             `protobuf:"varint,5,opt,name=numGC" json:"numGC,omitempty"`
	GoVersion            string             `protobuf:"bytes,6,opt,name=goVersion" json:"goVersion,omitempty"`
	NumGoroutines        uint32             `protobuf:"varint,7,opt,name=numGoroutines" json:"numGoroutines,omitempty"`
	NumSessions          uint32             `protobuf:"varint,8,opt,name=numSessions" json:"numSessions,omitempty"`
	Uptime               *duration.Duration `protobuf:"bytes,9,opt,name=uptime" json:"uptime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SystemStats) Reset()         { *m = SystemStats{} }
func (m *SystemStats) String() string { return proto.CompactTextString(m) }
func (*SystemStats) ProtoMessage()    {}
func (*SystemStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_system_1b356edd64c42dec, []int{1}
}
func (m *SystemStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStats.Unmarshal(m, b)
}
func (m *SystemStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStats.Marshal(b, m, deterministic)
}
func (dst *SystemStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStats.Merge(dst, src)
}
func (m *SystemStats) XXX_Size() int {
	return xxx_messageInfo_SystemStats.Size(m)
}
func (m *SystemStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStats.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStats proto.InternalMessageInfo

func (m *SystemStats) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SystemStats) GetAllocMem() uint64 {
	if m != nil {
		return m.AllocMem
	}
	return 0
}

func (m *SystemStats) GetTotalAllocMem() uint64 {
	if m != nil {
		return m.TotalAllocMem
	}
	return 0
}

func (m *SystemStats) GetSystemMem() uint64 {
	if m != nil {
		return m.SystemMem
	}
	return 0
}

func (m *SystemStats) GetNumGC() uint32 {
	if m != nil {
		return m.NumGC
	}
	return 0
}

func (m *SystemStats) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *SystemStats) GetNumGoroutines() uint32 {
	if m != nil {
		return m.NumGoroutines
	}
	return 0
}

func (m *SystemStats) GetNumSessions() uint32 {
	if m != nil {
		return m.NumSessions
	}
	return 0
}

func (m *SystemStats) GetUptime() *duration.Duration {
	if m != nil {
		return m.Uptime
	}
	return nil
}

func init() {
	proto.RegisterType((*SystemStatsResponse)(nil), "system.SystemStatsResponse")
	proto.RegisterType((*SystemStats)(nil), "system.SystemStats")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SystemService service

type SystemServiceClient interface {
	GetSystemStats(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*SystemStatsResponse, error)
}

type systemServiceClient struct {
	cc *grpc.ClientConn
}

func NewSystemServiceClient(cc *grpc.ClientConn) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetSystemStats(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	out := new(SystemStatsResponse)
	err := grpc.Invoke(ctx, "/system.SystemService/GetSystemStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SystemService service

type SystemServiceServer interface {
	GetSystemStats(context.Context, *Authentication) (*SystemStatsResponse, error)
}

func RegisterSystemServiceServer(s *grpc.Server, srv SystemServiceServer) {
	s.RegisterService(&_SystemService_serviceDesc, srv)
}

func _SystemService_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Authentication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetSystemStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetSystemStats(ctx, req.(*Authentication))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "system.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemStats",
			Handler:    _SystemService_GetSystemStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}

func init() { proto.RegisterFile("system.proto", fileDescriptor_system_1b356edd64c42dec) }

var fileDescriptor_system_1b356edd64c42dec = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x51, 0x4f, 0xfa, 0x30,
	0x14, 0xc5, 0xff, 0xf0, 0x87, 0x01, 0xc5, 0xf9, 0x50, 0x4c, 0xac, 0xd3, 0x28, 0x21, 0x3e, 0x60,
	0x62, 0x46, 0xc4, 0x4f, 0x80, 0x92, 0xe0, 0x8b, 0x2f, 0x23, 0x31, 0xd1, 0xb7, 0x02, 0x97, 0xb9,
	0x64, 0x6d, 0x97, 0xf5, 0x96, 0xc4, 0x2f, 0xe6, 0xe7, 0x33, 0xeb, 0x3a, 0x18, 0xc6, 0xc7, 0x73,
	0xfa, 0xbb, 0xf7, 0x9e, 0xf4, 0x90, 0x13, 0xfd, 0xa5, 0x11, 0x44, 0x98, 0xe5, 0x0a, 0x15, 0xf5,
	0x4a, 0x15, 0xf8, 0x31, 0x48, 0xc8, 0x79, 0x5a, 0xda, 0xc1, 0x4d, 0xac, 0x54, 0x9c, 0xc2, 0xc4,
	0xaa, 0x95, 0xd9, 0x4e, 0x30, 0x11, 0xa0, 0x91, 0x8b, 0xcc, 0x01, 0xd7, 0xbf, 0x81, 0x8d, 0xc9,
	0x39, 0x26, 0x4a, 0x96, 0xef, 0x23, 0x49, 0x06, 0x4b, 0xbb, 0x79, 0x89, 0x1c, 0x75, 0x04, 0x3a,
	0x53, 0x52, 0x03, 0xbd, 0x27, 0x2d, 0x01, 0xc8, 0x59, 0x63, 0xd8, 0x18, 0xf7, 0xa7, 0x2c, 0xac,
	0xae, 0xce, 0x61, 0xcb, 0x4d, 0x8a, 0x15, 0x17, 0x59, 0x8a, 0xde, 0x91, 0xb6, 0x2e, 0xc6, 0x59,
	0xd3, 0xe2, 0x83, 0xd0, 0x45, 0xaf, 0x6f, 0x2e, 0x89, 0xd1, 0x77, 0x93, 0xf4, 0x6b, 0x36, 0x65,
	0xa4, 0xb3, 0x83, 0x5c, 0x27, 0x4a, 0xda, 0x5b, 0xbd, 0xa8, 0x92, 0x34, 0x20, 0x5d, 0x9e, 0xa6,
	0x6a, 0xfd, 0x0a, 0xc2, 0xee, 0x6d, 0x45, 0x7b, 0x4d, 0x6f, 0x89, 0x8f, 0x0a, 0x79, 0x3a, 0xab,
	0x80, 0xff, 0x16, 0x38, 0x36, 0xe9, 0x15, 0xe9, 0x95, 0x41, 0x0a, 0xa2, 0x65, 0x89, 0x83, 0x41,
	0xcf, 0x48, 0x5b, 0x1a, 0xb1, 0x78, 0x66, 0xed, 0x61, 0x63, 0xec, 0x47, 0xa5, 0x28, 0x66, 0x62,
	0xf5, 0xe6, 0x12, 0x79, 0x36, 0xd1, 0xc1, 0x28, 0xee, 0x16, 0x98, 0xca, 0x95, 0xc1, 0x44, 0x82,
	0x66, 0x1d, 0x3b, 0x7b, 0x6c, 0xd2, 0x21, 0xe9, 0x4b, 0x23, 0x96, 0xa0, 0x8b, 0x19, 0xcd, 0xba,
	0x96, 0xa9, 0x5b, 0xf4, 0x81, 0x78, 0x26, 0x2b, 0xaa, 0x62, 0x3d, 0xfb, 0x63, 0x17, 0x61, 0x59,
	0x53, 0x58, 0xd5, 0x14, 0xce, 0x5d, 0x4d, 0x91, 0x03, 0xa7, 0xef, 0xc4, 0x77, 0xff, 0x06, 0xf9,
	0x2e, 0x59, 0x03, 0x7d, 0x21, 0xa7, 0x0b, 0xc0, 0xfa, 0x5f, 0x9e, 0xef, 0x6b, 0x9a, 0x19, 0xfc,
	0x04, 0x89, 0xc9, 0xda, 0xee, 0x08, 0x2e, 0xff, 0x2a, 0xc4, 0x55, 0x38, 0xfa, 0xf7, 0xd4, 0xfd,
	0xf0, 0x84, 0xda, 0x40, 0xaa, 0x57, 0x9e, 0xbd, 0xff, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xef,
	0x72, 0x52, 0x2f, 0x7c, 0x02, 0x00, 0x00,
}
