// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserRequest struct {
	Auth                 *Authentication `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	User                 *User           `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6b59638221f10ce2, []int{0}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (dst *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(dst, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetAuth() *Authentication {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *UserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserResponse struct {
	Meta                 *DefaultResponse `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	User                 *User            `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6b59638221f10ce2, []int{1}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetMeta() *DefaultResponse {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserIDRequest struct {
	Auth                 *DefaultResponse `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	ID                   uint32           `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserIDRequest) Reset()         { *m = UserIDRequest{} }
func (m *UserIDRequest) String() string { return proto.CompactTextString(m) }
func (*UserIDRequest) ProtoMessage()    {}
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6b59638221f10ce2, []int{2}
}
func (m *UserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIDRequest.Unmarshal(m, b)
}
func (m *UserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIDRequest.Marshal(b, m, deterministic)
}
func (dst *UserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIDRequest.Merge(dst, src)
}
func (m *UserIDRequest) XXX_Size() int {
	return xxx_messageInfo_UserIDRequest.Size(m)
}
func (m *UserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserIDRequest proto.InternalMessageInfo

func (m *UserIDRequest) GetAuth() *DefaultResponse {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *UserIDRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UserEmailRequest struct {
	Auth                 *DefaultResponse `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Email                string           `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserEmailRequest) Reset()         { *m = UserEmailRequest{} }
func (m *UserEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UserEmailRequest) ProtoMessage()    {}
func (*UserEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6b59638221f10ce2, []int{3}
}
func (m *UserEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEmailRequest.Unmarshal(m, b)
}
func (m *UserEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEmailRequest.Marshal(b, m, deterministic)
}
func (dst *UserEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEmailRequest.Merge(dst, src)
}
func (m *UserEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UserEmailRequest.Size(m)
}
func (m *UserEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserEmailRequest proto.InternalMessageInfo

func (m *UserEmailRequest) GetAuth() *DefaultResponse {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *UserEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type User struct {
	// @inject_tag: storm:"id,increment"
	ID        uint32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty" storm:"id,increment"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	// @inject_tag: storm:"unique"
	Email                string               `protobuf:"bytes,4,opt,name=email" json:"email,omitempty" storm:"unique"`
	Password             string               `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	IsAdmin              bool                 `protobuf:"varint,6,opt,name=isAdmin" json:"isAdmin,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updatedAt" json:"updatedAt,omitempty"`
	LastSessionAt        *timestamp.Timestamp `protobuf:"bytes,9,opt,name=lastSessionAt" json:"lastSessionAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_6b59638221f10ce2, []int{4}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetLastSessionAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastSessionAt
	}
	return nil
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*UserIDRequest)(nil), "user.UserIDRequest")
	proto.RegisterType((*UserEmailRequest)(nil), "user.UserEmailRequest")
	proto.RegisterType((*User)(nil), "user.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetOwnUser(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserByID(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserByEmail(ctx context.Context, in *UserEmailRequest, opts ...grpc.CallOption) (*UserResponse, error)
	UpdateOwnUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	DeleteOwnUser(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*DefaultResponse, error)
	DeleteUserByID(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*DefaultResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetOwnUser(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/GetOwnUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByID(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/GetUserByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByEmail(ctx context.Context, in *UserEmailRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/GetUserByEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateOwnUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/UpdateOwnUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteOwnUser(ctx context.Context, in *Authentication, opts ...grpc.CallOption) (*DefaultResponse, error) {
	out := new(DefaultResponse)
	err := grpc.Invoke(ctx, "/user.UserService/DeleteOwnUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserByID(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*DefaultResponse, error) {
	out := new(DefaultResponse)
	err := grpc.Invoke(ctx, "/user.UserService/DeleteUserByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetOwnUser(context.Context, *Authentication) (*UserResponse, error)
	GetUserByID(context.Context, *UserIDRequest) (*UserResponse, error)
	GetUserByEmail(context.Context, *UserEmailRequest) (*UserResponse, error)
	UpdateOwnUser(context.Context, *UserRequest) (*UserResponse, error)
	DeleteOwnUser(context.Context, *Authentication) (*DefaultResponse, error)
	DeleteUserByID(context.Context, *UserIDRequest) (*DefaultResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetOwnUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Authentication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetOwnUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetOwnUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetOwnUser(ctx, req.(*Authentication))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByID(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByEmail(ctx, req.(*UserEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateOwnUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateOwnUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateOwnUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateOwnUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteOwnUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Authentication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteOwnUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteOwnUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteOwnUser(ctx, req.(*Authentication))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserByID(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOwnUser",
			Handler:    _UserService_GetOwnUser_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _UserService_GetUserByID_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _UserService_GetUserByEmail_Handler,
		},
		{
			MethodName: "UpdateOwnUser",
			Handler:    _UserService_UpdateOwnUser_Handler,
		},
		{
			MethodName: "DeleteOwnUser",
			Handler:    _UserService_DeleteOwnUser_Handler,
		},
		{
			MethodName: "DeleteUserByID",
			Handler:    _UserService_DeleteUserByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_6b59638221f10ce2) }

var fileDescriptor_user_6b59638221f10ce2 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x9b, 0x34, 0x4d, 0x93, 0x09, 0x8e, 0x60, 0x41, 0x60, 0x59, 0x08, 0x2a, 0x9f, 0x2a,
	0x51, 0xb9, 0x52, 0xb9, 0x54, 0x42, 0x42, 0xb8, 0x32, 0xaa, 0x72, 0x00, 0x24, 0x97, 0x72, 0xa8,
	0xb8, 0x6c, 0xe3, 0x49, 0xba, 0x92, 0xed, 0x35, 0xde, 0x35, 0x15, 0x4f, 0xc0, 0xfb, 0xf1, 0x44,
	0x68, 0xc7, 0x5e, 0x3b, 0x3d, 0x38, 0x91, 0x7a, 0xf3, 0x8c, 0xff, 0xff, 0x9b, 0x19, 0xfb, 0x07,
	0xa8, 0x14, 0x96, 0x41, 0x51, 0x4a, 0x2d, 0xd9, 0xc8, 0x3c, 0x7b, 0xce, 0x1a, 0x73, 0x2c, 0x79,
	0x5a, 0x37, 0xbd, 0xb7, 0x6b, 0x29, 0xd7, 0x29, 0x9e, 0x52, 0x75, 0x5b, 0xad, 0x4e, 0xb5, 0xc8,
	0x50, 0x69, 0x9e, 0x15, 0xb5, 0xc0, 0xbf, 0x81, 0xd9, 0xb5, 0xc2, 0x32, 0xc6, 0x5f, 0x15, 0x2a,
	0xcd, 0xde, 0xc1, 0x88, 0x57, 0xfa, 0xce, 0x1d, 0x1c, 0x0d, 0x8e, 0x67, 0x67, 0xaf, 0x02, 0x4b,
	0x0b, 0x2b, 0x7d, 0x87, 0xb9, 0x16, 0x4b, 0xae, 0x85, 0xcc, 0x63, 0x12, 0xb1, 0x37, 0x40, 0x33,
	0xdd, 0x21, 0x89, 0x21, 0xa0, 0x65, 0x88, 0x46, 0x7d, 0xff, 0x27, 0x3c, 0xa9, 0xd9, 0xaa, 0x90,
	0xb9, 0x42, 0x76, 0x02, 0xa3, 0x0c, 0x35, 0x6f, 0xe0, 0x6e, 0x0b, 0x8f, 0x70, 0xc5, 0xab, 0x54,
	0x5b, 0x5d, 0x4c, 0xaa, 0x9d, 0xf4, 0x2f, 0xe0, 0x98, 0x6a, 0x11, 0xd9, 0xdd, 0x4f, 0x1e, 0xec,
	0xbe, 0x05, 0x4f, 0xcb, 0xcf, 0x61, 0xb8, 0x88, 0x08, 0xee, 0xc4, 0xc3, 0x45, 0xe4, 0xff, 0x80,
	0xa7, 0x06, 0xf7, 0x39, 0xe3, 0x22, 0x7d, 0x1c, 0xf1, 0x05, 0x1c, 0xa0, 0x71, 0x13, 0x74, 0x1a,
	0xd7, 0x85, 0xff, 0x6f, 0x08, 0x23, 0x03, 0x6e, 0x06, 0x0e, 0xec, 0x40, 0xf6, 0x1a, 0xa6, 0x2b,
	0x51, 0x2a, 0xfd, 0x95, 0x67, 0xd8, 0x58, 0xba, 0x06, 0xf3, 0x60, 0x92, 0xf2, 0xe6, 0xe5, 0x3e,
	0xbd, 0x6c, 0xeb, 0x6e, 0xd0, 0x68, 0x63, 0x90, 0x71, 0x14, 0x5c, 0xa9, 0x7b, 0x59, 0x26, 0xee,
	0x41, 0xed, 0xb0, 0x35, 0x73, 0xe1, 0x50, 0xa8, 0x30, 0xc9, 0x44, 0xee, 0x8e, 0x8f, 0x06, 0xc7,
	0x93, 0xd8, 0x96, 0xec, 0x1c, 0xa6, 0xcb, 0x12, 0xb9, 0xc6, 0x24, 0xd4, 0xee, 0x21, 0xdd, 0xe9,
	0x05, 0x75, 0x68, 0x02, 0x1b, 0x9a, 0xe0, 0xbb, 0x0d, 0x4d, 0xdc, 0x89, 0x8d, 0xb3, 0x2a, 0x92,
	0xc6, 0x39, 0xd9, 0xed, 0x6c, 0xc5, 0xec, 0x13, 0x38, 0xe6, 0x96, 0x2b, 0x54, 0x4a, 0xc8, 0x3c,
	0xd4, 0xee, 0x74, 0xa7, 0xfb, 0xa1, 0xe1, 0xec, 0xef, 0x7e, 0x1d, 0xdb, 0x2b, 0x2c, 0x7f, 0x8b,
	0x25, 0xb2, 0x0f, 0x00, 0x97, 0xa8, 0xbf, 0xdd, 0xe7, 0xf4, 0xa5, 0xfb, 0x62, 0xeb, 0xb1, 0x8d,
	0x10, 0x35, 0xff, 0xce, 0xdf, 0x63, 0xe7, 0x30, 0xbb, 0x44, 0x6d, 0x9a, 0x17, 0x7f, 0x16, 0x11,
	0x7b, 0xde, 0x89, 0xda, 0x6c, 0xf5, 0x38, 0x3f, 0xc2, 0xbc, 0x75, 0x52, 0x70, 0xd8, 0xcb, 0x4e,
	0xb7, 0x99, 0xa4, 0xde, 0xc9, 0xce, 0x35, 0x7d, 0x15, 0xbb, 0xf9, 0xb3, 0x4d, 0xd9, 0x36, 0x67,
	0x04, 0x4e, 0x84, 0x29, 0x76, 0xce, 0xde, 0x9b, 0x7b, 0x53, 0xeb, 0xef, 0xb1, 0x10, 0xe6, 0x35,
	0x65, 0xfb, 0xf1, 0x5b, 0x10, 0x17, 0x93, 0x9b, 0x71, 0x26, 0x13, 0x4c, 0xd5, 0xed, 0x98, 0x7e,
	0xdb, 0xfb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64, 0xfc, 0xfa, 0x6f, 0x94, 0x04, 0x00, 0x00,
}
