// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserUpdate user update
// swagger:model UserUpdate
type UserUpdate struct {

	// ID
	ID *int64 `json:"ID,omitempty"`

	// created at
	CreatedAt *int64 `json:"createdAt,omitempty"`

	// email
	Email *string `json:"email,omitempty"`

	// first name
	FirstName *string `json:"firstName,omitempty"`

	// has avatar
	HasAvatar *bool `json:"hasAvatar,omitempty"`

	// is admin
	IsAdmin *bool `json:"isAdmin,omitempty"`

	// last name
	LastName *string `json:"lastName,omitempty"`

	// last session at
	LastSessionAt *int64 `json:"lastSessionAt,omitempty"`

	// password
	Password *string `json:"password,omitempty"`

	// updated at
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
}

// Validate validates this user update
func (m *UserUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUpdate) UnmarshalBinary(b []byte) error {
	var res UserUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
