// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// User user
// swagger:model User
type User struct {

	// ID
	ID int64 `json:"ID,omitempty" gorm:"primary_key;auto_increment"`

	// created
	Created int64 `json:"created,omitempty"`

	// email
	Email string `json:"email,omitempty" gorm:"unique_index"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// is admin
	IsAdmin bool `json:"isAdmin,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// last session
	LastSession int64 `json:"lastSession,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// retain files after deletion
	RetainFilesAfterDeletion bool `json:"retainFilesAfterDeletion,omitempty"`

	// updated
	Updated int64 `json:"updated,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
